### ISSUE TITLE
Broken docs link.

### ISSUE THREAD

**Issue by demitri** [Starlink/starlink-pyast#39]
The user docs appear to have disappeared. :(

<http://timj.github.io/starlink-pyast/pyast.html>

**Comment by sfgraves** [comment]
They've moved to http://starlink.github.io/starlink-pyast/pyast.html , when we moved the repo into the Starlink main collection. I should go through and fix any remaining broken links though -- do you happen to remember where you came across any?

**Comment by demitri** [comment]
Yes; sorry, I should have noted:

* <https://github.com/Starlink/starlink-pyast>
* <http://starlink.eao.hawaii.edu/starlink/AST> (under "Documentation")

Thanks!

**Comment by sfgraves** [comment]
I fixed the main README, and the one remaining wrong link on the starlink.eao.hawaii.edu page that I could find. Thanks for noticing this, and please reopen if you come across any more links we need to fix.
